#!/bin/sh

# set wallpaper, adjust colorscheme with pywal and set picture in fastfetch [fetch]

#WALLPAPER_DIR="$HOME/Pictures/wallpapers/"
#CURRENT_WALL=$(awk '/path/ {print $3}' .config/hypr/hyprpaper.conf)

# get a random wallpaper that is not the current one
#WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# select wallpaper [yazi 'bg']
WALLPAPER="$(copyq read 0)"

# load new wallpaper in hyprpaper.conf
echo 'wallpaper {' > $HOME/.config/hypr/hyprpaper.conf
echo '  monitor = HDMI-A-1' >> $HOME/.config/hypr/hyprpaper.conf
echo '  path =' "$WALLPAPER" >> $HOME/.config/hypr/hyprpaper.conf
echo '}' >> $HOME/.config/hypr/hyprpaper.conf

# set color theme
wal -i "$WALLPAPER" --cols16

# cava get colors and reload
wal_cava -c ~/.config/cava/config -G 7 -i ~/.cache/wal/colors.json && pkill -USR2 cava

# waybar get colors and restart
killall -SIGUSR2 waybar

# set wallpaper in 'fast'fetch
fastfetch --logo "$WALLPAPER" --logo-type sixel --logo-width 50 --logo-height 19 --logo-padding-top 1

# reload hyprpaper
pkill -9 hyprpaper 2>/dev/null
sleep 0.5
exec hyprpaper &

